name: 🤖 Auto studio-v3.json ✨

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 13 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Update studio-v3.json with changes from sanity.io/exchange
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci --no-scripts
      - run: npm run sync:studio-v3
      - uses: EndBug/add-and-commit@d4d066316a2a85974a05efb42be78f897793c6d9 # tag=v9
        with:
          commit: --no-verify
          message: 'chore(bot): sync:studio-v3 [skip ci][skip release]'
          default_author: github_actions
