name: 🤖 Auto studio-v3.json ✨

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 13 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Update studio-v3.json with changes from sanity.io/exchange
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci --no-scripts
      - run: npm run sync:studio-v3
      - uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b # tag=v9
        with:
          commit: --no-verify
          message: 'chore(bot): sync:studio-v3 [skip ci][skip release]'
          default_author: github_actions
